name: CI

on:
        push:
                branches:
                        - "trunk"
        pull_request_review:
                branches:
                        - "trunk"
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - name: checkout
                          uses: actions/checkout@v4
                        - name: install valgrind
                          run: |
                                  sudo apt-get update
                                  sudo apt-get install valgrind
                        - name: make
                          run: make BUILDDIR=build
                        - name: make check
                          run: make BUILDDIR=check check
                        - name: make memcheck
                          run: make BUILDDIR=memcheck memcheck
                        - name: store artifact
                          uses: actions/upload-artifact@v4
                          with:
                                  name: binary
                                  path: build/osu-bbcode
