name: CI

on:
  push:
    branches:
      - "trunk"
  pull_request_review:
    branches:
      - "trunk"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check
    - name: store artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: osu-bbcode
