name: CI

on:
        push:
                branches:
                        - "trunk"
        pull_request:
                branches:
                        - "trunk"
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - name: checkout
                          uses: actions/checkout@v4
                          with:
                                  submodules: recursive
                        - name: make
                          run: make BUILDDIR=build
                        - name: make check
                          run: make BUILDDIR=check check
                        - name: store artifact
                          uses: actions/upload-artifact@v4
                          with:
                                  name: binary
                                  path: build/osu-bbcode
